### ISSUE TITLE
https://notify-api.line.me/api/notify: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by chouwenhan** [utahta/go-linenotify#1]
How should I avoid client authorize certificate? Thanks

**Comment by chouwenhan** [comment]
How should I avoid client authorize certificate? Thanks

**Comment by utahta** [comment]
Umm...I don't know but you can google it [like this](https://www.google.com/search?q="x509%3A+certificate+signed+by+unknown+authority").
